# WARNING - Generated by {fusen} from dev/0-dev_mf_api.Rmd: do not edit by hand

#' ---
#' title: "Tests pour get_precip_stations"
#' tags: [test]
#' ---

#' @test
testthat::test_that("get_precip_stations retourne NULL avec token invalide", {
  testthat::skip_if_offline()
  result <- get_precip_stations(c(56), token = "token_invalide")
  testthat::expect_null(result[["56"]])
})

