# WARNING - Generated by {fusen} from dev/0-dev_mf_api.Rmd: do not edit by hand

#' title: "Tests pour telecharger_commande_csv" 
#' tags: [test] 
#'  ---
#' @test 
testthat::test_that("Erreur si identifiant invalide", 
                    { testthat::skip_if_offline() 
                      testthat::expect_error( 
                        telecharger_commande_csv("id_invalide", 
                                                 token = "token_invalide"), 
                                              "Erreur lors du téléchargement" ) })

