# WARNING - Generated by {fusen} from dev/0-dev_mf_api.Rmd: do not edit by hand

#' ---
#' title: "Tests pour les fonctions API Météo France"
#' tags: [test]
#' ---

#' @test
testthat::test_that("get_mf_token retourne le token si défini", {
  withr::with_envvar(c(MF_TOKEN = "abc123"), {
    token <- get_mf_token()
    testthat::expect_equal(token, "abc123")
  })
})

#' @test
testthat::test_that("get_mf_token échoue si le token est vide", {
  withr::with_envvar(c(MF_TOKEN = ""), {
    testthat::expect_error(get_mf_token(), "n'est pas defini")
  })
})


