# WARNING - Generated by {fusen} from dev/0-dev_mf_api.Rmd: do not edit by hand

#' @title Commander des données horaires
#' @description Interroge l'API Météo France pour commander des données horaires pour une station entre deux dates.
#' @param id_station Identifiant de la station (chaîne de caractères).
#' @param date_debut Date de début de la période (format ISO 8601).
#' @param date_fin Date de fin de la période (format ISO 8601).
#' @param token Jeton d'accès à l'API Météo France (OAuth2).
#' @return Un objet JSON contenant l'identifiant de la commande.
#' @export
#' @examples
#' if (interactive()) {
#'   token <- get_mf_token()
#'   commande <- commande_donnees_horaires(
#'     id_station = "56004001",
#'     date_debut = "2024-01-01T00:00:00Z",
#'     date_fin   = "2025-01-01T00:00:00Z",
#'     token = token
#'   )
#'   print(commande)
#' }
commande_donnees_horaires <- function(id_station, date_debut, date_fin, token) {
  base_url <- "https://public-api.meteofrance.fr/public/DPClim/v1/commande-station/horaire"
  
  url <- paste0(
    base_url,
    "?id-station=", id_station,
    "&date-deb-periode=", URLencode(date_debut, reserved = TRUE),
    "&date-fin-periode=", URLencode(date_fin, reserved = TRUE)
  )
  
 response <- httr::GET(
  url = url,
  httr::add_headers(
    Accept = "*/*",
    apikey = token  # <-- clé correcte ici
  )
)

  
  if (httr::status_code(response) == 202) {
    return(as.character(unlist(httr::content(response, as = "parsed", type = "application/json"))))
  } else {
    stop(paste("Erreur HTTP", httr::status_code(response), ":", httr::content(response, as = "text")))
  }
}


