# WARNING - Generated by {fusen} from dev/0-dev_mf_api.Rmd: do not edit by hand

#' @title Récupérer le token Météo France
#' @description Cette fonction lit la variable d'environnement `MF_TOKEN` et retourne sa valeur.
#' @return Une chaîne de caractères contenant le token.
#' @export
#' @examples
#' if (interactive()) {
#'   Sys.setenv(MF_TOKEN = "fake_token")
#'   token <- get_mf_token()
#'   print(token)
#' }
get_mf_token <- function() {
  token <- Sys.getenv("MF_TOKEN")
  if (token == "") {
    stop("Le token Meteo France n'est pas defini. Utilisez Sys.setenv(MF_TOKEN = 'votre_token')")
  }
  return(token)
}
