# WARNING - Generated by {fusen} from dev/0-dev_mf_api.Rmd: do not edit by hand

#' get_precip_stations
#'
#' @param departements Vecteur avec la liste des codes de départements
#' @param token : token d'accès à l'API météo France (disponible gratuitement sur le site https://portail-api.meteofrance.fr/)
#' @param duree : soit horaire si on veut récupérer les données horaires, soit quotidienne pour les données quotidiennes(par défaut duree="horaire")
#'
#' @return
#' Data Frame avec les stations météo disponibles
#' @export
#'
#' @examples
#' if (interactive()) {
#'   token <- Sys.getenv("MF_TOKEN")  # ou demander à l'utilisateur
#'   stations <- get_precip_stations(c(56, 35), token)
#'   print(stations)
#' }
get_precip_stations <- function(departements, token, duree="horaire") {
  
     # Vérification du paramètre 'duree'
     duree <- tolower(duree)
     if (!duree %in% c("horaire", "quotidienne")) {
       stop("Le paramètre 'duree' doit être soit 'horaire', soit 'quotidienne'.")
     }
  
  if (duree=="horaire")
  {base_url <- "https://public-api.meteofrance.fr/public/DPClim/v1/liste-stations/horaire"}
  else if (duree=="quotidienne")
  {base_url <- "https://public-api.meteofrance.fr/public/DPClim/v1/liste-stations/quotidienne"}
  all_results <- list()

  for (dep in departements) {
    url <- paste0(base_url, "?id-departement=", dep, "&parametre=precipitation")

response <- httr::GET(
  url = url,
  httr::add_headers(
    Accept = "*/*",
    apikey = token  # <-- clé correcte ici
  )
)


    if (httr::status_code(response) == 200) {
      content_data <- httr::content(response, as = "parsed", type = "application/json")
      all_results[[as.character(dep)]] <- content_data
    } else {
      warning(paste("Erreur pour le departement", dep, ":", httr::status_code(response)))
      all_results[[as.character(dep)]] <- NULL
    }
  }

  
all_results <- purrr::imap_dfr(
all_results,
 ~ dplyr::bind_rows(.x) %>% dplyr::mutate(departement = .y)
)

# Vérifie et renomme les colonnes si nécessaire
if (!all(c("lon", "lat") %in% names(all_results))) {
  if (all(c("longitude", "latitude") %in% names(all_results))) {
    all_results <- dplyr::rename(all_results, lon = longitude, lat = latitude)
  } else {
    stop("Les colonnes de coordonnées 'lon' et 'lat' (ou 'longitude' et 'latitude') sont manquantes.")
  }
}

# Conversion en objet sf
all_results <- sf::st_as_sf(all_results, coords = c("lon", "lat"), crs = 4326)

  
  return(all_results)
}


