# WARNING - Generated by {fusen} from dev/0-dev_mf_api.Rmd: do not edit by hand

#' @title Informations sur une station Météo France 
#' @description Renvoie l'historique de la station Météo France. 
#' @param id_station Identifiant de la station (chaîne de caractères).
#' @param token Jeton d'accès à l'API Météo France. 
#' @return Un data.frame contenant les informations sur la station. 
#' @export 
#' @examples 
#' if (interactive()) { 
#' token <- Sys.getenv("MF_TOKEN") 
#' infos_station <- get_infos_stations("35281001", token) 
#' print(infos_station)
#'  }
get_infos_stations <- function(id_station, token) {
  # Construire l'URL
  url <- paste0("https://public-api.meteofrance.fr/public/DPClim/v1/information-station?id-station=", id_station)
  
  # Requête GET
  response <- httr::GET(
    url = url,
    httr::add_headers(
      Accept = "*/*",
      apikey = token
    )
  )
  
  # Vérifier le statut
  if (httr::status_code(response) != 200) {
    stop("Erreur lors du téléchargement : ", httr::status_code(response))
  }
  
  # Lire le contenu texte
   content_data <- httr::content(response, as = "parsed", type = "application/json")%>%
     unlist
  
  # # Lire le CSV en data.frame
  # df <- read.csv2(text = contenu_csv, stringsAsFactors = FALSE)
  # 
  # # conversion des dates
  # df$DATE <- as.POSIXct(as.character(df$DATE), format = "%Y%m%d%H", tz = "UTC")
  
  return(content_data)
}

