# WARNING - Generated by {fusen} from dev/0-dev_mf_api.Rmd: do not edit by hand

#' @title Télécharger un fichier CSV depuis une commande Météo France 
#' @description Télécharge et lit un fichier CSV à partir d'un identifiant de commande. 
#' @param id_cmde Identifiant de la commande (chaîne de caractères). 
#' @param token Jeton d'accès à l'API Météo France. 
#' @return Un data.frame contenant les données du fichier CSV. 
#' @details
#' Correspondance des colonnes principales :
#' - POSTE : Identifiant de la station météo
#' - DATE : Date et heure de l’observation (format AMJH)
#' - RR1 : Précipitations horaires (mm)
#' - QRR1 : Qualité de la donnée RR1
#' - T : Température instantanée (°C)
#' - QT : Qualité de la température
#' - TN : Température minimale horaire
#' - TX : Température maximale horaire
#' - FF : Vitesse moyenne du vent
#' - QFF : Qualité de la vitesse du vent
#' - DD : Direction du vent (degrés)
#' - FXI : Rafale instantanée maximale
#' - PMER : Pression au niveau de la mer (hPa)
#' - UV_INDICE : Indice UV
#' - N : Nébulosité totale
#' - CL : Nébulosité basse
#' - CM : Nébulosité moyenne
#' - CH : Nébulosité haute
#' @export 
#' @examples 
#' if (interactive()) { 
#' token <- Sys.getenv("MF_TOKEN") 
#' df <- telecharger_commande_csv("2025006008357", token) 
#' head(df) 
#'  }
telecharger_commande_csv <- function(id_cmde, token) {
  # Construire l'URL
  url <- paste0("https://public-api.meteofrance.fr/public/DPClim/v1/commande/fichier?id-cmde=", id_cmde)
  
  # Requête GET
  response <- httr::GET(
    url = url,
    httr::add_headers(
      Accept = "*/*",
      apikey = token
    )
  )
  
  # Vérifier le statut
  if (httr::status_code(response) != 201) {
    stop("Erreur lors du téléchargement : ", httr::status_code(response))
  }
  
  # Lire le contenu texte
  contenu_csv <- httr::content(response, as = "text", encoding = "UTF-8")
  
  # Lire le CSV en data.frame
  df <- read.csv2(text = contenu_csv, stringsAsFactors = FALSE)
  
   # Détection automatique du format de la colonne DATE
if ("DATE" %in% names(df)) {
  # Vérifie la longueur des chaînes de date
  date_lengths <- unique(nchar(na.omit(as.character(df$DATE))))
  
  if (all(date_lengths == 10)) {
    # Format horaire : YYYYMMDDHH
    df$DATE <- as.POSIXct(df$DATE, format = "%Y%m%d%H", tz = "UTC")
  } else if (all(date_lengths == 8)) {
    # Format quotidien : YYYYMMDD
    df$DATE <- as.Date(as.character(df$DATE), format = "%Y%m%d")
  } else {
    warning("Format de date non reconnu. La colonne DATE est laissée telle quelle.")
  }
}

  
  
  return(df)
}

